### ISSUE TITLE
Incorrect information about sunrise and sunset

### ISSUE THREAD

**Issue by Mogost** [atareao/my-weather-indicator#22]
![wrong](https://cloud.githubusercontent.com/assets/721963/18981399/18d856fa-8708-11e6-9180-11546a3894dc.png)
I think it happened because it did not taken into consideration the time zone. Tomsk is in GMT+7 TZ.
These data differ by approximately 7 hours.
Time in system and TZ is correct. 
![image](https://cloud.githubusercontent.com/assets/721963/18981463/91f144b6-8708-11e6-8b67-383e2bfe4e99.png)
$ date
September 30 12:25:11 KRAT 2016
KRAT – Krasnoyarsk Time (Tomsk and Krasnoyarsk in the same timezone)

**Comment by camilova** [comment]
I was getting the same error for my local timezone for UTC - 4
It was because I dont use python, and on my installation there was no `pytz` nor `tzlocal` libraries, and the weather script could not get the local timezone.
The solution for me was pretty simple, simple install missing python libraries and restart the widget and timezone will work. In my case I use ubuntu based distro, I simply did on a `terminal`:

`sudo apt install python-pip` (to install libraries for python)
`pip install pytz`
`pip install tzlocal`

Restart widget and enjoy!

**Comment by atareao** [comment]
Added dependencies
