### ISSUE TITLE
Time displayed on widget is not based on system time

### ISSUE THREAD

**Issue by BangDroid** [atareao/my-weather-indicator#53]
Time should not be dependent on internet connection.
My laptop spends part of it's day offline, during these times when I boot up the widget will display the last time shown and continue counting minute by minute. Only once reconnected to the internet, opening Preferences and clicking Ok (not cancel) will the widget and time update correctly.

**Comment by enigma9o7** [comment]
I have this issue too.   If I start it after the internet is connected, it works right.  But if I have it autostart (which starts it before network connection is established) then the widget clock will be wrong, even when the forecast updates.

(Also it would be nice if the forecast auto-updated when the network connection became active, instead of just saying N/A for 15 minutes....)

**Comment by enigma9o7** [comment]
This annoys me every time I reboot.  I'm a little surprised it's been a repeatable issue since 2018.

**Comment by atareao** [comment]
Not in the last version
